---
- name: Add domains and users in iRedMail
  hosts: all 
  become: yes

  vars_files:
    - user.yaml  # Include the YAML file with domain and user details

  tasks:
    - name: Ensure /tmp directory exists on the remote host
      file:
        path: /tmp
        state: directory

    - name: Copy create_domain_SQL.sh to the remote host
      copy:
        src: ./create_domain_SQL.sh
        dest: /root/iRedMail-1.7.1/tools/create_domain_SQL.sh
        mode: '0755'


    - name: Generate domain SQL script on the remote host
      shell: "bash /root/iRedMail-1.7.1/tools/create_domain_SQL.sh {{ item.name }} 'My Domain' 20 20 >> /tmp/domains.sql"
      with_items: "{{ domains }}"
      register: domain_sql_output
      ignore_errors: yes  # Ignore errors to prevent failure on already existing domains

    - name: Add domain SQL script to MySQL on the remote host
      mysql_db:
        name: vmail
        state: import
        target: /tmp/domains.sql
      when: domain_sql_output is not failed
      ignore_errors: yes


